### ISSUE TITLE
proposal for hash literal

### ISSUE THREAD

**Issue by jmptrader** [haifenghuang/monkey#12]
Hello Mr. haifenghuang,

My sugesstion is that for expresion in hash literal, 

h = { "a"=>1, "b"=>2, "c"=>2}

is better to use,

h = { "a" : 1, "b" : 2, "c" : 2}

because you have de arrow functions

accord with this

https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Funciones/Arrow_functions

is more familiar to use "=>" that "->".

Thank's,
JM

**Comment by haifenghuang** [comment]
Thanks for you suggestions, I'll think about it.

**Comment by haifenghuang** [comment]
I've made the modification according to your suggestions, now you can try the latest source.

**Comment by jmptrader** [comment]
Mr. haifenghuang, 

Thanks very much to you for this. 

JM
