### ISSUE TITLE
simple c-like for loop not run

### ISSUE THREAD

**Issue by jmptrader** [haifenghuang/monkey#15]
Hi,

The next code from monkey console , not run

`let a = 0; for (a = 0; a < 10; a++) { if (a == 3) { a = 7; continue } println(a) };`

That is wrong?

JM

**Comment by jmptrader** [comment]
Hi,

Reviewing the code in parser.go file , in method

```
func (p *Parser) parseCForLoopExpression(curToken token.Token) ast.Expression {
 ....
 if init == nil && cond == nil && update == nil {
		loop := &ast.ForEverLoop{Token: curToken}
		loop.Block = p.parseBlockStatement()
		result = loop
	} else {
		loop := &ast.ForLoop{Token: curToken}
		loop.Block = p.parseBlockStatement()
		result = loop
	}

        ...
}

```
I change code by

```
func (p *Parser) parseCForLoopExpression(curToken token.Token) ast.Expression {
 ....

	if init == nil && cond == nil && update == nil {
		loop := &ast.ForEverLoop{Token: curToken}
		loop.Block = p.parseBlockStatement()
		result = loop 
	} else {
		loop := &ast.ForLoop{Token: curToken,
			Init: init,
			Cond: cond,
			Update: update,
		}
		loop.Block = p.parseBlockStatement()
		result = loop
	}

        ....
}
```

Now code run,

am I right ?

Thanks'
JM

**Comment by haifenghuang** [comment]
Yes, You're right. In the body of `parseCForLoopExpression`, the three pre-declared variables `init`, `cond` and `update` are assigned, but never used. 

In commit `55885e1`, the source is correct, but in commit `7e56c90`, i changed the code, but forgot to assign the three variables back to struct `ForLop`.

Thanks a lot for pointing this!
